2025-03-24 22:07:41,003 - custodian.policy - INFO - policy:add_tag_vault_untagged resource:huaweicloud.cbr-vault region: count:0 time:0.00
2025-03-25 09:51:17,352 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 127, in response_hook
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/root/custodian/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cbr.ap-southeast-1.myhuaweicloud.com/v3/ap-southeat-1/vaults?limit=100&offset=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/huawei_custodian/cloud-custodian/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 153, in resources
    resources = self._fetch_resources(q)
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 172, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 74, in get_resources
    return self.query.filter(self.manager, **query)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 28, in filter
    resources = self._pagination_limit_offset(m, enum_op, path)
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 45, in _pagination_limit_offset
    response = self._invoke_client_enum(client, enum_op, request)
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 62, in _invoke_client_enum
    return getattr(client, enum_op)(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 2457, in list_vault
    return self._call_api(**http_info)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 4792, in _call_api
    return self.do_http_request(**kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 480, in do_http_request
    response = self._do_http_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 531, in _do_http_request_sync
    response = self._http_client.do_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 100, in do_request_sync
    self.response_error_hook_factory()(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 129, in response_hook
    self._exception_handler.handle_exception(httpError.request, httpError.response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/exceptions/exception_handler.py", line 75, in handle_exception
    raise exceptions.ClientRequestException(response.status_code, sdk_error) if response.status_code < 500 \
        else exceptions.ServerResponseException(response.status_code, sdk_error)
huaweicloudsdkcore.exceptions.exceptions.ClientRequestException: ClientRequestException - {status_code:401,request_id:960e93538567b035fa32ecebaca2d52e,error_code:APIGW.0301,error_msg:Incorrect IAM authentication information: get token error,status:400,encoded_authorization_message:None }
2025-03-25 09:52:50,576 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 127, in response_hook
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/root/custodian/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cbr.ap-southeast-1.myhuaweicloud.com/v3/ap-southeat-1/vaults?limit=100&offset=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/huawei_custodian/cloud-custodian/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 153, in resources
    resources = self._fetch_resources(q)
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 172, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 74, in get_resources
    return self.query.filter(self.manager, **query)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 28, in filter
    resources = self._pagination_limit_offset(m, enum_op, path)
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 45, in _pagination_limit_offset
    response = self._invoke_client_enum(client, enum_op, request)
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 62, in _invoke_client_enum
    return getattr(client, enum_op)(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 2457, in list_vault
    return self._call_api(**http_info)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 4792, in _call_api
    return self.do_http_request(**kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 480, in do_http_request
    response = self._do_http_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 531, in _do_http_request_sync
    response = self._http_client.do_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 100, in do_request_sync
    self.response_error_hook_factory()(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 129, in response_hook
    self._exception_handler.handle_exception(httpError.request, httpError.response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/exceptions/exception_handler.py", line 75, in handle_exception
    raise exceptions.ClientRequestException(response.status_code, sdk_error) if response.status_code < 500 \
        else exceptions.ServerResponseException(response.status_code, sdk_error)
huaweicloudsdkcore.exceptions.exceptions.ClientRequestException: ClientRequestException - {status_code:401,request_id:e7170225dbe554243c6ea87f2322a921,error_code:APIGW.0301,error_msg:Incorrect IAM authentication information: get token error,status:400,encoded_authorization_message:None }
2025-03-25 09:55:19,793 - custodian.policy - INFO - policy:add_tag_vault_untagged resource:huaweicloud.cbr-vault region: count:3 time:0.00
2025-03-25 09:55:21,410 - custodian.policy - INFO - policy:add_tag_vault_untagged action:cbrvaultaddtags resources:3 execution_time:1.62
